# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
krlogit_fn_trunc <- function(par, Utrunc, D, y, lambda) {
    .Call('KRLS2_krlogit_fn_trunc', PACKAGE = 'KRLS2', par, Utrunc, D, y, lambda)
}

#' @export
krlogit_gr_trunc <- function(par, Utrunc, D, y, lambda) {
    .Call('KRLS2_krlogit_gr_trunc', PACKAGE = 'KRLS2', par, Utrunc, D, y, lambda)
}

#' @export
euc_dist <- function(x1, x2) {
    .Call('KRLS2_euc_dist', PACKAGE = 'KRLS2', x1, x2)
}

#' @export
kern_gauss_1d <- function(x1, x2, b) {
    .Call('KRLS2_kern_gauss_1d', PACKAGE = 'KRLS2', x1, x2, b)
}

#' @export
kern_gauss <- function(x, b) {
    .Call('KRLS2_kern_gauss', PACKAGE = 'KRLS2', x, b)
}

#' @export
new_gauss_kern <- function(newx, oldx, b) {
    .Call('KRLS2_new_gauss_kern', PACKAGE = 'KRLS2', newx, oldx, b)
}

#' @export
mult_diag <- function(x, d) {
    .Call('KRLS2_mult_diag', PACKAGE = 'KRLS2', x, d)
}

#' @export
krlogit_gr_trunc2 <- function(par, Utrunc, D, y, lambda, n) {
    .Call('KRLS2_krlogit_gr_trunc2', PACKAGE = 'KRLS2', par, Utrunc, D, y, lambda, n)
}

#' @export
eigsym <- function(x) {
    .Call('KRLS2_eigsym', PACKAGE = 'KRLS2', x)
}

#' @export
lambda_search <- function(tol, l, u, y, eigvals, eigvecs, eigtrunc) {
    .Call('KRLS2_lambda_search', PACKAGE = 'KRLS2', tol, l, u, y, eigvals, eigvecs, eigtrunc)
}

#' @export
solve_for_c_ls_trunc <- function(y, Utrunc, D, lambda) {
    .Call('KRLS2_solve_for_c_ls_trunc', PACKAGE = 'KRLS2', y, Utrunc, D, lambda)
}

#' @export
solve_for_c_ls <- function(y, K, lambda) {
    .Call('KRLS2_solve_for_c_ls', PACKAGE = 'KRLS2', y, K, lambda)
}

#' @export
pwmfx <- function(k, x, coefhat, vcovc, p, b) {
    .Call('KRLS2_pwmfx', PACKAGE = 'KRLS2', k, x, coefhat, vcovc, p, b)
}

